test_square (__main__.TestExercice) ... ERROR
test_square_root (__main__.TestExercice) ... FAIL

======================================================================
ERROR: test_square (__main__.TestExercice)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_exercice.py", line 17, in test_square
    output_exo = list(map(exercice.square, self.numbers))
  File "/home/runner/work/c01_ch3_exercice1-pdamours/c01_ch3_exercice1-pdamours/exercice.py", line 12, in square
    return squared
NameError: name 'squared' is not defined

======================================================================
FAIL: test_square_root (__main__.TestExercice)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_exercice.py", line 33, in test_square_root
    'Failed to calculate square roots'
AssertionError: Lists differ: [None, None, None, None, None, None, None,[553 chars]None] != [0.0, 1.0, 1.4142135623730951, 1.732050807[1699 chars]0662]

First differing element 0:
None
0.0

Diff is 2946 characters long. Set self.maxDiff to None to see it. : Failed to calculate square roots

----------------------------------------------------------------------
Ran 2 tests in 0.012s

FAILED (failures=1, errors=1)
